apiVersion: apps/v1
kind: Deployment
metadata:
  name: feladat-neve
spec:
  replicas: 3
  selector:
    matchLabels:
      almafa: my-pod-label
  template:
    metadata:
      labels:
        almafa: my-pod-label
    spec:
      containers:
        - name: hello-app
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: feladat-service2
spec:
  selector:
    almafa: my-pod-label
  ports:
    - port: 80
      targetPort: 8080
